### PR TITLE
Unvendor Eigen, Sundials, and Boost on *nix

### LINKED ISSUE #30: Use vendored SUNDIALS rather than compiling our own
### Comment:

Ref https://github.com/stan-dev/math/pull/2861

### PR DESCRIPTION
**Pull request by WardBrian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #30

### CODE REVIEW

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
A lot of the heavy lifting was some upstream tweaks by other people.

I am on the fence whether or not this is really a great idea - for header-only things like Eigen, there's no real harm in having multiple of them in one environment (e.g. one vendored inside CmdStan and one in the normal conda place), but this would force you to have the game Eigen version for the entire environment, since I have it pinned to exactly the versions Stan uses.

**Comment by maresb** [comment]
Are the vendored versions still present for fallback, or completely removed?

**Comment by WardBrian** [comment]
I delete them as part of the build script here, but that isn't a necessary step I suppose. I don't see the benefit of leaving them if we do take this approach however

**Comment by maresb** [comment]
Is there much point to unvendoring them if the pins are exact?

**Comment by WardBrian** [comment]
Closing for now, may reconsider in future

**Pull request closed without merging**
