### PR TITLE
Try clang post general availability

### PR DESCRIPTION
**Pull request by WardBrian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

#31 again

### CODE REVIEW

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
Getting hung up on 

```
lld-link: error: could not open 'D:bldcmdstan_1719500406710_build_env/lib/clang/18/lib/windows/clang_rt.builtins-x86_64.lib': no such file or directory
```

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
I still want to try this on a local windows machine before merging

**Review by maresb — APPROVED** [review]
This looks like it was a lot of work, and is way over my head, so I can't offer much in terms of critical review.

I don't have Windows, so I can't help there either.

But this looks like a great step into the future! Thanks!!!

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
This was working before, but I think something broke with the newer clang. 

```
2024-11-11T21:11:12.8404481Z lld-link: error: undefined symbol: class tbb::detail::d1::concurrent_unordered_map<struct std::pair<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::thread::id>, class stan::math::profile_info, struct stan::math::internal::hash_profile_key, struct stan::math::internal::equal_profile_key, class tbb::detail::d1::tbb_allocator<struct std::pair<struct std::pair<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::thread::id> const, class stan::math::profile_info>>> & __cdecl get_stan_profile_data(void)
2024-11-11T21:11:12.8407039Z >>> referenced by src/cmdstan/main.o:($ehgcr_92_595)
```

**Comment by WardBrian** [comment]
@isuruf --

That is one of functions which are supplied by the code generated by the stan compiler. So in the failing invocation

`clang++  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe -D_CRT_SECURE_NO_WARNINGS -nostdlib -fms-runtime-lib=dll -fuse-ld=lld -fno-aligned-allocation -Wno-misleading-indentation  -std=c++17 -m64 -D_UCRT -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs -Wno-int-in-bool-context -Wno-attributes -Wno-ignored-attributes      -I D:/bld/cmdstan_1731362182504/_test_env/Library/include/     -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.84.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -D_REENTRANT -DBOOST_DISABLE_ASSERTS -D_BOOST_LGAMMA    -D_USE_MATH_DEFINES -D_GLIBCXX11_USE_C99_COMPLEX  -DBOOST_DISABLE_ASSERTS   -DTBB_INTERFACE_NEW  -DTBB_INTERFACE_NEW    -nostdlib -Wl,-defaultlib:D:/bld/cmdstan_1731362182504/_test_env/lib/clang/18/lib/windows/clang_rt.builtins-x86_64.lib       -Wl,-L,"D:/bld/cmdstan_1731362182504/_test_env/Library/lib/ " -Wl,--disable-new-dtags       examples/bernoulli/bernoulli.o src/cmdstan/main.o  -static-libgcc     -ltbb   stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_idas.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a   -o examples/bernoulli/bernoulli.exe`

The implementation is in `examples/bernoulli/bernoulli.o`

Do you think it is related that the warnings from the linker are reported to be from `lld-link`, despite me just requesting plain `lld` in the `-fuse-ld` argument?

**Comment by isuruf** [comment]
> `examples/bernoulli/bernoulli.o src/cmdstan/main.o`

Shouldn't it be the other way since `main.o` requires `examples/bernoulli/bernoulli.o`?

**Comment by WardBrian** [comment]
73cd7a7b2df105fb19f81efc260a0ec44e1e965c was me trying the other order, but the same error occurred. So far as I can tell, all modern linkers don't care about that sort of thing any more

**Comment by WardBrian** [comment]
If my memory is correct it was the same, but it seems the logs don’t live very long to go check

**Comment by isuruf** [comment]
Can you try again?

**Comment by WardBrian** [comment]
Tried again. Invocation:

`clang++  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe -D_CRT_SECURE_NO_WARNINGS -nostdlib -fms-runtime-lib=dll -fuse-ld=lld -fno-aligned-allocation -Wno-misleading-indentation  -std=c++17 -m64 -D_UCRT -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs -Wno-int-in-bool-context -Wno-attributes -Wno-ignored-attributes      -I D:/bld/cmdstan_1731595311684/_test_env/Library/include/     -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.84.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -D_REENTRANT -DBOOST_DISABLE_ASSERTS -D_BOOST_LGAMMA    -D_USE_MATH_DEFINES -D_GLIBCXX11_USE_C99_COMPLEX  -DBOOST_DISABLE_ASSERTS   -DTBB_INTERFACE_NEW  -DTBB_INTERFACE_NEW    -nostdlib -Wl,-defaultlib:D:/bld/cmdstan_1731595311684/_test_env/lib/clang/18/lib/windows/clang_rt.builtins-x86_64.lib       -Wl,-L,"D:/bld/cmdstan_1731595311684/_test_env/Library/lib/ " -Wl,--disable-new-dtags       src/cmdstan/main.o examples/bernoulli/bernoulli.o  -static-libgcc     -ltbb   stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_idas.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a   -o examples/bernoulli/bernoulli.exe`

(note `src/cmdstan/main.o examples/bernoulli/bernoulli.o`, so the patch did work)

Same error:
`lld-link: error: undefined symbol: class tbb::detail::d1::concurrent_unordered_map<struct std::pair<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::thread::id>, class stan::math::profile_info, struct stan::math::internal::hash_profile_key, struct stan::math::internal::equal_profile_key, class tbb::detail::d1::tbb_allocator<struct std::pair<struct std::pair<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::thread::id> const, class stan::math::profile_info>>> & __cdecl get_stan_profile_data(void)`

**Comment by isuruf** [comment]
Is it possible to print the source code for examples/bernoulli/bernoulli.o ?

**Comment by WardBrian** [comment]
I can. I do know a priori that the content of that source file is exactly the same before this pr as it is now, however, and also does not vary by platform, so I can also just assert that it will be this:

<details><summary>Details</summary>
<p>

```c++

// Code generated by stanc v2.35.0
#include <stan/model/model_header.hpp>
namespace bernoulli_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 7> locations_array__ =
  {" (found before start of program)",
  " (in 'bernoulli.stan', line 6, column 2 to column 31)",
  " (in 'bernoulli.stan', line 9, column 2 to column 21)",
  " (in 'bernoulli.stan', line 10, column 2 to column 23)",
  " (in 'bernoulli.stan', line 2, column 2 to column 17)",
  " (in 'bernoulli.stan', line 3, column 8 to column 9)",
  " (in 'bernoulli.stan', line 3, column 2 to column 35)"};
class bernoulli_model final : public model_base_crtp<bernoulli_model> {
 private:
  int N;
  std::vector<int> y;
 public:
  ~bernoulli_model() {}
  bernoulli_model(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "bernoulli_model_namespace::bernoulli_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 4;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 4;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 4;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 5;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 6;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      y = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 6;
      y = context__.vals_i("y");
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 6;
      stan::math::check_less_or_equal(function__, "y", y, 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1;
  }
  inline std::string model_name() const final {
    return "bernoulli_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.35.0",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bernoulli_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 1;
      theta = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(0, 1, lp__);
      {
        current_statement__ = 2;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(theta, 1, 1));
        current_statement__ = 3;
        lp_accum__.add(stan::math::bernoulli_lpmf<propto__>(y, theta));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bernoulli_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 1;
      theta = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(0, 1, lp__);
      {
        current_statement__ = 2;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(theta, 1, 1));
        current_statement__ = 3;
        lp_accum__.add(stan::math::bernoulli_lpmf<propto__>(y, theta));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "bernoulli_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double theta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      theta = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(0, 1, lp__);
      out__.write(theta);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 1;
      theta = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, theta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "theta", "double",
        std::vector<size_t>{});
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 1;
      theta = context__.vals_r("theta")[(1 - 1)];
      out__.write_free_lub(0, 1, theta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"theta"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "theta");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "theta");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1;
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1;
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = bernoulli_model_namespace::bernoulli_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return bernoulli_model_namespace::profiles__;
}
#endif

```

</p>
</details>  

What are you hoping to find?

**Comment by WardBrian** [comment]
During build:
`2024-11-14T14:44:12.8915356Z     tbb-devel:          2021.13.0-h053bfa6_0         conda-forge`

during test:

`2024-11-14T15:08:28.4505170Z     tbb-devel:          2022.0.0-h47441b3_0              conda-forge`

I think there's some syntax I'm not remembering for pinning this, I suspect the issue will be whenever the major version changes here?

**Comment by WardBrian** [comment]
This isn't happening on other platforms, I'm guessing because the name mangling might not use the fully expanded namespace, but rather respect `usings`? Either way, it looks like the issue is not actually a runtime one, since the ABI of the type did not appear to change [when the `d1` became `d2`:](https://github.com/oneapi-src/oneTBB/commit/c89df93c5fdb40a1e20d2b135e8eec6f185e1291#diff-9685eb6486b87576253406ff8ea414a94e8341eaef21295a99c3cc2195bf122c)

**Comment by maresb** [comment]
@WardBrian, perhaps you're looking for `pin-compatible`, for example [here](https://github.com/conda-forge/numba-feedstock/blob/24c85216de6d49852e2d3af43240629eea734238/recipe/meta.yaml#L55C26-L55C29)?

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
Thanks @maresb -- I knew such a thing was possible, but I can never remember the magic syntax. Trying that now

**Comment by WardBrian** [comment]
It looks like `pin_compatible` resolved to `tbb-devel >= 2021.13.0`, which includes 2022.0.0, so the same result occured.

@isuruf is there some other form of pinning I should be doing?

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
Now I'm getting a (non-deterministic?) error during testing where Eigen can't find `cmath`. No clue what to do about that

**Comment by isuruf** [comment]
Should be fixed by https://github.com/conda-forge/vc-feedstock/pull/89

**Comment by WardBrian** [comment]
Still getting it, @isuruf

```
In file included from <stdin>:1:
C:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\um\windows.h:171:10: fatal error: 'excpt.h' file not found
  171 | #include <excpt.h>
      |          ^~~~~~~~~
1 error generated.
clang++  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe -D_CRT_SECURE_NO_WARNINGS -nostdlib -fms-runtime-lib=dll -fuse-ld=lld -fno-aligned-allocation -Wno-misleading-indentation  -std=c++17 -m64 -D_UCRT -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs -Wno-int-in-bool-context -Wno-attributes -Wno-ignored-attributes      -I D:/bld/cmdstan_1731941736835/_test_env/Library/include/     -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.84.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -D_REENTRANT -DBOOST_DISABLE_ASSERTS -D_BOOST_LGAMMA    -D_USE_MATH_DEFINES -D_GLIBCXX11_USE_C99_COMPLEX  -DBOOST_DISABLE_ASSERTS   -DTBB_INTERFACE_NEW  -DTBB_INTERFACE_NEW     -c -MT src/cmdstan/main.o -M -E -MG -MP -MF src/cmdstan/main.d src/cmdstan/main.cpp
In file included from <stdin>:1:
C:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\um\windows.h:171:10: fatal error: 'excpt.h' file not found
  171 | #include <excpt.h>
      |          ^~~~~~~~~
1 error generated.

--- Compiling the main object file. This might take up to a minute. ---
clang++  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe -D_CRT_SECURE_NO_WARNINGS -nostdlib -fms-runtime-lib=dll -fuse-ld=lld -fno-aligned-allocation -Wno-misleading-indentation  -std=c++17 -m64 -D_UCRT -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs -Wno-int-in-bool-context -Wno-attributes -Wno-ignored-attributes      -I D:/bld/cmdstan_1731941736835/_test_env/Library/include/     -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.84.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -D_REENTRANT -DBOOST_DISABLE_ASSERTS -D_BOOST_LGAMMA    -D_USE_MATH_DEFINES -D_GLIBCXX11_USE_C99_COMPLEX  -DBOOST_DISABLE_ASSERTS   -DTBB_INTERFACE_NEW  -DTBB_INTERFACE_NEW     -c -o src/cmdstan/main.o src/cmdstan/main.cpp
stan/lib/stan_math/lib/eigen_3.4.0\Eigen\src/Core/util/Macros.h:679:10: fatal error: 'cmath' file not found
  679 | #include <cmath>
      |          ^~~~~~~
1 error generated.
```


Weirdly, this is only failing during the test which is also using python/cmdstanpy downstream.

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Another PR: https://github.com/conda-forge/clang-win-activation-feedstock/pull/49

**Comment by isuruf** [comment]
> It seems like it would be bad for end users if they could just get "unlucky" with MSVC versions.

This happens only when `CONDA_BUILD` is set where we are very strict about versions used. Users would need VS2022 or do `conda install vs2019_win-64` if the user has `VS2019`.

> Is there something specific about the Python test that fails, while the other doesn't seem to?

With the include of `stdlib('c')` we require VS2019 and when unbounded in tests, it tries to find VS2022.

**Comment by WardBrian** [comment]
> Users would need VS2022 or do conda install vs2019_win-64 if the user has VS2019.

I'm not sure how to read this. Are you saying users would need to do this (read: go out of their way) to get problems, or to get good behavior? 

My hope is that in replacing the current, mingw based, windows build that the user story is still the same, e.g., they can `conda install cmdstanpy` on an otherwise clean machine and boom, they can compile a Stan model first to C++ and then all the way down to an executable, without extra steps. Is this PR on the right track to allow that?

**Comment by WardBrian** [comment]
Related to my above question, is there any good way to have a version of this available for testing, or to let users pick which C++ toolchain they'd like to use? I'm imagining something like how you can pick between MPI implementations

**Comment by isuruf** [comment]
If users have VS2022, it'll work. If users have VS2019, they have to install `vs2019_win-64` conda package. If they have neither, they need to install Visual Studio.

>  is there any good way to have a version of this available for testing

Sure. You can put them into `conda-forge/label/cmdstan_dev`. See https://conda-forge.org/docs/maintainer/knowledge_base/#creating-a-pre-release-build

> let users pick which C++ toolchain they'd like to use?

You can have two variants of the same package.

**Comment by WardBrian** [comment]
Ah, I didn’t realize conda couldn’t install visual studio for them. That probably makes this PR a non starter unfortunately

**Comment by WardBrian** [comment]
If users would need their own MSVC version, this is probably not worth pursuing

**Pull request closed without merging**
