### PR TITLE
Try UCRT gcc on Windows

### LINKED ISSUE #31: TODO: Investigate using ucrt-based clang on Windows
### Comment:

Seems successful based on https://gist.github.com/WardBrian/ebbd85e8dfe9619068ec2edf5d6265cb

May need to have an option other than `make`?

### PR DESCRIPTION
**Pull request by WardBrian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Would close #31

### CODE REVIEW

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
@isuruf -- does using the UCRT gcc on Windows not give access to executables called `gcc`/`g++`?

**Comment by isuruf** [comment]
`gxx_win-64` doesn't. It's in `gxx`.

**Comment by WardBrian** [comment]
My latest attempt was using `gxx`. Are they not available in cmd prompts I wonder?

**Comment by WardBrian** [comment]
@isuruf - is g++ on Windows 32 bit? I'm getting OOM errors I wouldn't expect

**Comment by isuruf** [comment]
>  is g++ on Windows 32 bit?

No, it's x86_64.

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
Superseded by #55

**Pull request closed without merging**
