### PR TITLE
Add linux-aarch64 platform

### PR DESCRIPTION
**Pull request by WardBrian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)

See comment below

* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This adds the aarch64 platform to the build. It uses a separate download of cmdstan packaged for this architecture. 

More architectures will be coming: https://github.com/stan-dev/stanc3/pull/936

### CODE REVIEW

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by WardBrian** [comment]
Here's a discussion on gitter about the build numbers:

> Brian Ward 14:33
If I'm adding a new build (adding linux-aarch64) but the existing recipes aren't changing at all, should I still increment the build number?
>
> Matthew R. Becker 14:33
> Not needed if the existing recipre builds are the same
> do double check this
> rerendering usually changes all of the CI files unless it was done very recently
> either way, our services will not upload duplicate builds
> 
> Brian Ward 14:34
> The feedstock is very new, created last week
> 
> Matthew R. Becker 14:34
> so even if you shipped different scripts with the same build number, users would not see them anyways
> got it
> sounds like you are fine to not increment the build number
> 
> Brian Ward 14:35
> Looking at the file changes, nothing about the ci changed except for the arch specific
> Thanks!
> 
> Matthew R. Becker 14:35
> ofc!

**Comment by WardBrian** [comment]
@maresb - if you could just take a brief look at this I'd appreciate it.

**Comment by maresb** [comment]
@WardBrian, looks great to me! But I'm not really qualified to review this though. If you truly want a second pair of eyes, then I'd ping isuruf and/or wolfv.

**Comment by WardBrian** [comment]
I was more just asking about obvious typos etc, I trust the CI/tests for the technical details of this sort of thing

**Pull request merged**
